// Generate src/lib/abi.ts from the Foundry artifacts so agents and tests share one ABI source.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../../contracts/out");
const load = (name: string) => JSON.parse(readFileSync(resolve(out, `${name}.sol/${name}.json`), "utf8"));
const eb = load("EvalBounty");
const arb = load("CentralizedArbitrator");
const cm = load("CommitteeArbitrator");
const src = `// AUTO-GENERATED by scripts/gen-abi.ts from contracts/out. Do not edit.
export const evalBountyAbi = ${JSON.stringify(eb.abi)} as const;
export const evalBountyBytecode = ${JSON.stringify(eb.bytecode.object)} as const;
export const arbitratorAbi = ${JSON.stringify(arb.abi)} as const;
export const arbitratorBytecode = ${JSON.stringify(arb.bytecode.object)} as const;
export const committeeAbi = ${JSON.stringify(cm.abi)} as const;
export const committeeBytecode = ${JSON.stringify(cm.bytecode.object)} as const;
`;
writeFileSync(resolve(here, "../src/lib/abi.ts"), src);
// Browser copy for the static dashboard: EvalBounty events + views, plus the arbitrator's Ruling-related events.
const dashAbi = [...eb.abi, ...arb.abi.filter((x: { type: string; name?: string }) => x.type === "event" && !eb.abi.some((y: { name?: string }) => y.name === x.name))];
writeFileSync(resolve(here, "../../dashboard/abi.js"), `// AUTO-GENERATED by agents/scripts/gen-abi.ts\nwindow.EVALBOUNTY_ABI = ${JSON.stringify(dashAbi)};\n`);
console.log("wrote src/lib/abi.ts and dashboard/abi.js");
