// EvalBounty dashboard. Static, read-only: reads contract events through a public RPC and renders them.
// No keys, no transactions. Config comes from ./config.js (generated by agents/src/deploy.ts).
import { createPublicClient, http, parseEventLogs, formatEther } from "https://esm.sh/viem@2.56.3";
import * as chains from "https://esm.sh/viem@2.56.3/chains";

const cfg = window.EVALBOUNTY_CONFIG;
const abi = window.EVALBOUNTY_ABI;
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const ZERO = "0x0000000000000000000000000000000000000000";
const STATUS = ["Open", "Committed", "Sampled", "Approved", "Delivered", "Disputed", "Settled", "Refunded", "Cancelled"];
const LIVE = new Set(["Committed", "Sampled", "Approved", "Delivered", "Disputed"]);
const CAT = {
  BountyCreated: "bounty", BountyCancelled: "bounty",
  Committed: "commit", CommitWithdrawn: "commit", SampleRevealed: "commit", SampleComplete: "commit", SampleApproved: "commit", SampleRejected: "commit",
  Delivered: "delivery", Accepted: "delivery",
  Disputed: "dispute", Dispute: "dispute", Evidence: "dispute", Ruling: "dispute", MetaEvidence: "dispute",
  Settled: "settle", Refunded: "settle", Split: "settle", Finalized: "settle", Withdrawn: "settle",
};
const CATS = [
  { key: "bounty", name: "Bounties", color: "var(--s-bounty)" },
  { key: "commit", name: "Commit & sample", color: "var(--s-commit)" },
  { key: "delivery", name: "Delivery", color: "var(--s-delivery)" },
  { key: "dispute", name: "Disputes", color: "var(--s-dispute)" },
  { key: "settle", name: "Settlement", color: "var(--s-settle)" },
  { key: "admin", name: "Admin", color: "var(--s-admin)" },
];
const catOf = (name) => CAT[name] ?? "admin";

// ---------- formatting ----------
const hasExplorer = !!cfg.explorerBase;
const short = (a) => (a ? `${a.slice(0, 6)}…${a.slice(-4)}` : "—");
const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const pct = (bps) => `${(Number(bps) / 100).toFixed(0)}%`;
const ethNum = (wei) => Number(formatEther(wei ?? 0n));
const eth = (wei, d = 4) => `${ethNum(wei).toFixed(d)} ETH`;
const fmtInt = (n) => Number(n).toLocaleString();
const EXT = `<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M6 3h7v7M13 3 5 11"/></svg>`;
function who(a) {
  const l = a?.toLowerCase();
  for (const [k, v] of Object.entries(cfg.agents ?? {})) if (v.toLowerCase() === l) return k.replace(/([A-Z])/g, " $1").toLowerCase();
  return "";
}
function identicon(a) {
  const h1 = parseInt(a.slice(2, 8), 16) % 360, h2 = parseInt(a.slice(8, 14), 16) % 360;
  return `<i class="id" style="background:linear-gradient(135deg,hsl(${h1} 70% 55%),hsl(${h2} 70% 45%))"></i>`;
}
function addr(a, { label = true } = {}) {
  if (!a || a === ZERO) return `<span class="faint">—</span>`;
  const inner = `${identicon(a)}${short(a)}${label && who(a) ? `<span class="who">${who(a)}</span>` : ""}`;
  return hasExplorer
    ? `<a class="addr" href="${cfg.explorerBase}/address/${a}" target="_blank" rel="noopener" data-tip="${a}" data-tip-mono>${inner}</a>`
    : `<span class="addr" data-tip="${a}" data-tip-mono>${inner}</span>`;
}
function tx(h, text = "tx") {
  return hasExplorer
    ? `<a class="tx" href="${cfg.explorerBase}/tx/${h}" target="_blank" rel="noopener" data-tip="tx ${h}" data-tip-mono>${text}${EXT}</a>`
    : `<span class="tx" data-tip="tx ${h}" data-tip-mono>${text}</span>`;
}
const timeOf = (sec) => new Date(Number(sec) * 1000);
const fmtTime = (sec) => timeOf(sec).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
const fmtDateTime = (sec) => timeOf(sec).toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" });
function rel(sec) {
  const d = Number(sec) * 1000 - Date.now(), a = Math.abs(d), u = a < 60e3 ? [1e3, "s"] : a < 3600e3 ? [60e3, "m"] : a < 86400e3 ? [3600e3, "h"] : [86400e3, "d"];
  const n = Math.round(a / u[0]);
  return d > 0 ? `in ${n}${u[1]}` : `${n}${u[1]} ago`;
}
function hexToBytes(h) { const s = h.slice(2); const out = new Uint8Array(s.length / 2); for (let i = 0; i < out.length; i++) out[i] = parseInt(s.substr(i * 2, 2), 16); return out; }
function parseTask(hex) { try { return JSON.parse(new TextDecoder().decode(hexToBytes(hex))); } catch { return null; } }

// ---------- narration (the agent log is the video's narration) ----------
function narrate(ev) {
  const a = ev.args;
  switch (ev.eventName) {
    case "BountyCreated": return `Buyer ${short(a.buyer)} posted bounty #${a.id}: ${a.spec.taskCount} ${esc(a.spec.domainTag)} tasks, reveal ${a.spec.sampleSize}, band ${esc(a.spec.weakModel)} ≤ ${pct(a.spec.weakMaxBps)} / ${esc(a.spec.strongModel)} ≥ ${pct(a.spec.strongMinBps)}, reward ${eth(a.reward)}.`;
    case "Committed": return `Seller ${short(a.seller)} committed to #${a.id}: root ${short(a.taskRoot)}, bundle hash ${short(a.bundleCommitment)}, bond ${eth(a.bond)}. Sample will be drawn from blockhash(${a.sampleBlock}).`;
    case "SampleRevealed": { const t = parseTask(a.task); return `#${a.id}: revealed task ${a.index}${t ? ` — “${esc(t.prompt.slice(0, 80))}${t.prompt.length > 80 ? "…" : ""}”` : ""}.`; }
    case "SampleComplete": return `#${a.id}: all sampled tasks revealed with valid Merkle proofs. Buyer has until ${fmtTime(a.approveBy)} to judge.`;
    case "SampleApproved": return `Buyer approved the sample of #${a.id}. Seller must deliver by ${fmtTime(a.deliverBy)}.`;
    case "SampleRejected": return `Buyer rejected the sample of #${a.id} from ${short(a.seller)}: “${esc(a.reason)}”. Bond returned, bounty reopened.`;
    case "CommitWithdrawn": return `Seller ${short(a.seller)} withdrew its commit on #${a.id}${a.penalty > 0n ? ` and paid a ${eth(a.penalty)} penalty` : ""}.`;
    case "Delivered": return `#${a.id}: ${fmtInt((a.ciphertext.length - 2) / 2)}-byte ciphertext delivered (hash ${short(a.ciphertextHash)}). Buyer has until ${fmtTime(a.verifyBy)} to accept or dispute.`;
    case "Accepted": return `Buyer accepted #${a.id}.`;
    case "Disputed": return `Buyer disputed #${a.id} (${a.kind === 0 ? "BadDelivery" : "ClaimsFailed"}), arbitration dispute ${a.disputeId}. Arbiter must rule by ${fmtTime(a.ruleBy)}.`;
    case "Ruling": return `Arbitrator ruled dispute ${a._disputeID}: ${["refused → split", "seller wins", "buyer wins"][Number(a._ruling)] ?? a._ruling}.`;
    case "Settled": return `#${a.id} settled: seller ${short(a.seller)} receives ${eth(a.sellerPayout)}, treasury fee ${eth(a.fee)}.`;
    case "Refunded": return `#${a.id} refunded: buyer ${short(a.buyer)} receives ${eth(a.buyerPayout)}.`;
    case "Split": return `#${a.id} split: buyer ${eth(a.buyerPayout)}, seller ${eth(a.sellerPayout)}.`;
    case "Finalized": return `#${a.id} finalized: ${esc(a.reason)}.`;
    case "Withdrawn": return `${short(a.account)} withdrew ${eth(a.amount)}.`;
    case "BountyCancelled": return `#${a.id} cancelled by its buyer.`;
    case "Evidence": return `Evidence submitted by ${short(a._party)}: ${esc(a._evidence.slice(0, 120))}`;
    case "Dispute": return `ERC-1497 dispute ${a._disputeID} registered with arbitrator ${short(a._arbitrator)}.`;
    case "MetaEvidence": return `Dispute policy published: ${esc(a._evidence)}`;
    case "OwnershipTransferred": return `Contract deployed; owner is ${short(a.newOwner)}.`;
    case "ArbitratorUpdated": return `Arbitrator set to ${short(a.arbitrator)}.`;
    default: return ev.eventName;
  }
}

// ---------- chain ----------
const chain = Object.values(chains).find((c) => c && typeof c === "object" && c.id === cfg.chainId) ?? chains.sepolia;
const client = createPublicClient({ chain, transport: http(cfg.rpcUrl) });
async function readMany(contracts) {
  if (!contracts.length) return [];
  if (chain.contracts?.multicall3) return client.multicall({ contracts });
  return Promise.all(contracts.map((c) => client.readContract(c).then((result) => ({ status: "success", result })).catch((error) => ({ status: "failure", error }))));
}
const blockTimes = new Map(); // blockNumber(string) -> unix seconds, cached across refreshes
async function fillBlockTimes(events) {
  const missing = [...new Set(events.map((e) => e.blockNumber.toString()))].filter((b) => !blockTimes.has(b));
  for (let i = 0; i < missing.length; i += 8) {
    await Promise.all(missing.slice(i, i + 8).map(async (bn) => { const b = await client.getBlock({ blockNumber: BigInt(bn) }); blockTimes.set(bn, Number(b.timestamp)); }));
  }
}
const tsOf = (e) => blockTimes.get(e.blockNumber.toString());

// ---------- motion ----------
const reduceMotion = matchMedia("(prefers-reduced-motion: reduce)").matches;
const tweens = new WeakMap();
const shown = {}; // last value shown per counter, so refreshes tween from the previous number
function tween(el, to, fmt, from = 0, dur = 1000) {
  if (!el) return;
  if (reduceMotion || from === to) { el.textContent = fmt(to); return; }
  cancelAnimationFrame(tweens.get(el));
  const t0 = performance.now();
  el.textContent = fmt(from);
  const step = (t) => {
    const p = Math.min(1, (t - t0) / dur), e = 1 - Math.pow(1 - p, 3);
    el.textContent = fmt(from + (to - from) * e);
    if (p < 1) tweens.set(el, requestAnimationFrame(step));
  };
  tweens.set(el, requestAnimationFrame(step));
}
function counter(key, el, to, fmt, opts = {}) {
  const from = shown[key] ?? opts.from ?? 0;
  shown[key] = to;
  tween(el, to, fmt, from, opts.dur);
}
let firstData = true; // entrance animations play once, on the first render with data

// ---------- state ----------
const S = { events: [], bounties: [], byId: {}, head: 0n, sellers: [], buyers: [], srep: [], brep: [], refreshedAt: null, error: null };
const UI = { tab: "bounties", range: "all", rangeManual: false, status: "all", q: "", expanded: new Set(), logCats: new Set(CATS.map((c) => c.key)), hiddenCats: new Set() };
let newFrom = Infinity; // index of the first event that arrived on the latest refresh

async function refresh() {
  try {
    const head = await client.getBlockNumber();
    const logs = await client.getLogs({ address: cfg.contractAddress, fromBlock: BigInt(cfg.deployBlock), toBlock: "latest" });
    const events = parseEventLogs({ abi, logs }).sort((x, y) => Number(x.blockNumber - y.blockNumber) || x.logIndex - y.logIndex);
    await fillBlockTimes(events);
    const count = Number(await client.readContract({ address: cfg.contractAddress, abi, functionName: "bountyCount" }));
    const bounties = (await readMany(Array.from({ length: count }, (_, i) => ({ address: cfg.contractAddress, abi, functionName: "getBounty", args: [BigInt(i)] })))).map((r) => (r.status === "success" ? r.result : null));
    const byId = {};
    for (const e of events) { const id = e.args?.id?.toString(); if (id !== undefined) (byId[id] ??= []).push(e); }
    const sellers = [...new Set(events.filter((e) => e.eventName === "Committed").map((e) => e.args.seller))];
    const buyers = [...new Set(events.filter((e) => e.eventName === "BountyCreated").map((e) => e.args.buyer))];
    const [srep, brep] = await Promise.all([
      readMany(sellers.map((a) => ({ address: cfg.contractAddress, abi, functionName: "sellerRep", args: [a] }))),
      readMany(buyers.map((a) => ({ address: cfg.contractAddress, abi, functionName: "buyerRep", args: [a] }))),
    ]);
    const prevLen = S.refreshedAt ? S.events.length : events.length;
    newFrom = events.length > prevLen ? prevLen : Infinity;
    Object.assign(S, { head, events, bounties, byId, sellers, buyers, srep: srep.map((r) => r.result ?? []), brep: brep.map((r) => r.result ?? []), refreshedAt: new Date(), error: null });
    if (!UI.rangeManual) setRange(autoRange(), false);
    window.__state = { events, bounties };
  } catch (err) {
    console.error(err);
    S.error = err.shortMessage ?? err.message;
  }
  renderAll();
}

// ---------- derived ----------
function bucketize(range) {
  const now = Math.floor(Date.now() / 1000);
  const first = S.events.length ? Math.min(...S.events.map(tsOf).filter(Boolean)) : now - 3600;
  let start, step;
  if (range === "1h") { step = 300; start = now - 12 * step; }
  else if (range === "6h") { step = 900; start = now - 24 * step; }
  else if (range === "24h") { step = 3600; start = now - 24 * step; }
  else if (range === "7d") { step = 6 * 3600; start = now - 28 * step; }
  else { const span = now - first; step = span <= 3 * 3600 ? 300 : span <= 12 * 3600 ? 900 : span <= 48 * 3600 ? 3600 : span <= 14 * 86400 ? 6 * 3600 : 86400; start = Math.min(first, now - 12 * step); }
  start = Math.floor(start / step) * step;
  const n = Math.ceil((now - start) / step) + 1;
  const buckets = Array.from({ length: n }, (_, i) => ({ t: start + i * step, step, counts: Object.fromEntries(CATS.map((c) => [c.key, 0])), total: 0 }));
  for (const e of S.events) { const t = tsOf(e); if (t === undefined || t < start) continue; const b = buckets[Math.min(n - 1, Math.floor((t - start) / step))]; b.counts[catOf(e.eventName)]++; b.total++; }
  return buckets;
}
// Pick the shortest window that has something to show: while tests run this lands on 1h.
function autoRange() {
  const now = Date.now() / 1000;
  const cnt = (w) => S.events.filter((e) => tsOf(e) >= now - w).length;
  if (cnt(3600) >= 4) return "1h";
  if (cnt(6 * 3600) >= 4) return "6h";
  if (cnt(86400) >= 1) return "24h";
  if (cnt(7 * 86400) >= 1) return "7d";
  return "all";
}
function setRange(r, manual) {
  UI.range = r; if (manual) UI.rangeManual = true;
  $$("#rangeSeg button").forEach((b) => b.setAttribute("aria-pressed", b.dataset.range === r));
}
const STAGE_EVENT = { created: "BountyCreated", committed: "Committed", sampled: "SampleComplete", approved: "SampleApproved", delivered: "Delivered", accepted: "Accepted", disputed: "Disputed", settled: "Settled", refunded: "Refunded", split: "Split" };
function stageCounts() {
  const c = {}; const ids = {};
  for (const k of Object.keys(STAGE_EVENT)) { c[k] = 0; ids[k] = []; }
  for (const [id, evs] of Object.entries(S.byId).sort((x, y) => Number(x[0]) - Number(y[0]))) {
    const names = new Set(evs.map((e) => e.eventName));
    for (const [k, ev] of Object.entries(STAGE_EVENT)) if (names.has(ev)) { c[k]++; ids[k].push(`#${id}`); }
  }
  c.ids = ids;
  return c;
}

// ---------- tiny SVG helpers ----------
function sparkline(series, color) {
  const w = 160, h = 44, pad = 4;
  const max = Math.max(...series) || 1, n = series.length;
  const x = (i) => pad + (i * (w - 2 * pad)) / Math.max(1, n - 1), y = (v) => h - pad - (v / max) * (h - 2 * pad);
  const pts = series.map((v, i) => `${x(i).toFixed(1)},${y(v).toFixed(1)}`);
  const line = `M${pts.join("L")}`;
  const area = `${line}L${x(n - 1).toFixed(1)},${h}L${x(0).toFixed(1)},${h}Z`;
  const gid = `g${Math.random().toString(36).slice(2, 8)}`;
  const dot = `<i class="dot" style="left:${((x(n - 1) / w) * 100).toFixed(2)}%;top:${((y(series[n - 1]) / h) * 100).toFixed(2)}%;background:${color}"></i><i class="guide"></i><i class="pt" style="background:${color};color:${color}"></i><span class="stip"></span>`;
  sparkline.last = { xs: series.map((_, i) => +((x(i) / w) * 100).toFixed(2)), ys: series.map((v) => +((y(v) / h) * 100).toFixed(2)) };
  return `<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="${gid}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${color}" stop-opacity=".28"/><stop offset="1" stop-color="${color}" stop-opacity="0"/></linearGradient></defs><path class="area" d="${area}" fill="url(#${gid})"/><path class="line" d="${line}" fill="none" stroke="${color}" stroke-width="1.5" vector-effect="non-scaling-stroke" stroke-linejoin="round"/></svg>${dot}`;
}
// Sparklines: 24 equal buckets from the first event to now, so the line shows the shape of the
// history rather than the chart's padded range.
function sparkSpan() {
  const now = Math.floor(Date.now() / 1000);
  const times = S.events.map(tsOf).filter((t) => t !== undefined);
  const first = times.length ? Math.min(...times) : now - 3600;
  const n = 24, step = Math.max(60, Math.ceil((now - first) / (n - 1)));
  return { start: first, step, n };
}
function cumulative(pick) {
  const { start, step, n } = sparkSpan();
  const out = new Array(n).fill(0);
  for (const e of S.events) { const t = tsOf(e); const v = pick(e); if (!v || t === undefined) continue; out[Math.min(n - 1, Math.max(0, Math.floor((t - start) / step)))] += v; }
  let acc = 0; return out.map((v) => (acc += v));
}
function perBucket(pick) {
  const { start, step, n } = sparkSpan();
  const out = new Array(n).fill(0);
  for (const e of S.events) { const t = tsOf(e); const v = pick(e); if (!v || t === undefined) continue; out[Math.min(n - 1, Math.max(0, Math.floor((t - start) / step)))] += v; }
  return out;
}

// ---------- render ----------
function renderAll() {
  const animate = firstData && !!S.refreshedAt;
  renderTop();
  // Do not yank a chart out from under the pointer: a hovered tile or chart keeps its state until the next refresh.
  if (!$("#stats .tile.scrub")) renderStats(animate);
  if (!$("#chart[data-active]")) renderChart(animate);
  renderFunnel(animate); renderBounties(); renderReputation(); renderLog();
  if (animate) firstData = false;
}

function renderTop() {
  const live = $("#live");
  if (S.error) live.innerHTML = `<span class="dot bad"></span><span>RPC error</span>`;
  else if (!S.refreshedAt) live.innerHTML = `<span class="dot wait"></span><span>connecting</span>`;
  else { const fresh = Number.isFinite(newFrom) ? S.events.length - newFrom : 0; live.innerHTML = `<span class="dot"></span><span>block ${fmtInt(S.head)}</span><span class="plus">+${fresh}</span>`; if (fresh) { live.classList.add("flash"); setTimeout(() => live.classList.remove("flash"), 4000); } }
  live.setAttribute("data-tip", S.error ? S.error : `${chain.name} via ${cfg.rpcUrl}\nrefreshes every 10 s`);
  $("#netBadge").textContent = chain.name;
  $("#refreshedAt").textContent = S.error ? `error: ${S.error}` : S.refreshedAt ? `refreshed ${S.refreshedAt.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" })}` : "connecting…";
  $("#stNet").textContent = `${chain.name} (${cfg.chainId})`;
  if (S.refreshedAt) counter("head", $("#stBlock"), Number(S.head), (v) => fmtInt(Math.round(v)), { from: Math.max(0, Number(S.head) - 400), dur: 1400 }); else $("#stBlock").textContent = "—";
  $("#stContract").innerHTML = addr(cfg.contractAddress, { label: false }) + (hasExplorer ? ` <a class="tx" href="${cfg.explorerBase}/address/${cfg.contractAddress}#code" target="_blank" rel="noopener">verified${EXT}</a>` : "");
  $("#stArb").innerHTML = addr(cfg.arbitratorAddress, { label: false });
  if (S.refreshedAt) { $("#stEvents").innerHTML = `<span id="stEventsN"></span> since block ${fmtInt(cfg.deployBlock)}`; counter("events", $("#stEventsN"), S.events.length, (v) => fmtInt(Math.round(v))); } else $("#stEvents").textContent = "—";
  const escrow = S.bounties.reduce((s, b) => (b && LIVE.has(STATUS[b.status]) || (b && STATUS[b.status] === "Open") ? s + b.reward + b.sellerBond + b.disputeBond : s), 0n);
  $("#stEscrow").textContent = S.refreshedAt ? eth(escrow) : "—";
  for (const [id, a] of [["#navContract", cfg.contractAddress], ["#navArbiter", cfg.arbitratorAddress], ["#ctaContract", cfg.contractAddress]]) {
    const el = $(id); if (hasExplorer) el.href = `${cfg.explorerBase}/address/${a}`; else { el.removeAttribute("href"); el.style.opacity = .5; el.title = "no block explorer for this chain"; }
  }
  if (cfg.videoUrl) { $("#navVideo").href = cfg.videoUrl; $("#navVideo").hidden = false; }
  if (cfg.repoUrl) { $("#navRepo").href = cfg.repoUrl; }
  $("#footContract").textContent = cfg.contractAddress;
}

function renderStats(animate) {
  if (!S.refreshedAt) {
    $("#stats").innerHTML = ["Bounties", "Reward volume", "Contract events", "Disputes"].map((k) => `<div class="tile"><div class="k">${k}</div><div class="v"><span class="skel">00</span></div><div class="spark skel" style="height:40px"></div><div class="foot skel">loading from the chain</div></div>`).join("");
    return;
  }
  const b = S.bounties.filter(Boolean);
  const now = Date.now() / 1000, day = 86400;
  const inWin = (from, to) => S.events.filter((e) => { const t = tsOf(e); return t >= from && t < to; });
  const last24 = inWin(now - day, now).length, prev24 = inWin(now - 2 * day, now - day).length, lastHour = inWin(now - 3600, now).length;
  const created24 = inWin(now - day, now).filter((e) => e.eventName === "BountyCreated").length;
  const settledVol = S.events.filter((e) => e.eventName === "Settled").reduce((s, e) => s + e.args.sellerPayout + e.args.fee, 0n);
  const escrowVol = S.events.filter((e) => e.eventName === "BountyCreated").reduce((s, e) => s + e.args.reward, 0n);
  const term = b.filter((x) => ["Settled", "Refunded", "Cancelled"].includes(STATUS[x.status])).length;
  const settled = b.filter((x) => STATUS[x.status] === "Settled").length;
  const disputes = S.events.filter((e) => e.eventName === "Disputed").length;
  const rulings = S.events.filter((e) => e.eventName === "Ruling").map((e) => Number(e.args._ruling));
  const delta = (cur, prev) => prev === 0 ? (cur > 0 ? { cls: "up", txt: `+${cur}` } : { cls: "flat", txt: "no change" }) : { cls: cur >= prev ? "up" : "down", txt: `${cur >= prev ? "+" : ""}${(((cur - prev) / prev) * 100).toFixed(0)}%` };
  const d = delta(last24, prev24);
  const tiles = [
    { k: "Bounties", num: b.length, fmt: (v) => fmtInt(Math.round(v)), sub: created24 ? { cls: "up", txt: `+${created24} in 24h` } : { cls: "flat", txt: `${b.filter((x) => LIVE.has(STATUS[x.status])).length} in progress` }, spark: cumulative((e) => e.eventName === "BountyCreated" ? 1 : 0), color: "var(--s-bounty)", foot: `${b.filter((x) => STATUS[x.status] === "Open").length} open · ${b.filter((x) => LIVE.has(STATUS[x.status])).length} in progress · ${term} closed` },
    { k: "Reward volume", num: ethNum(escrowVol), fmt: (v) => v.toFixed(3), unit: "ETH", sub: { cls: "flat", txt: `${ethNum(settledVol).toFixed(3)} paid out` }, spark: cumulative((e) => e.eventName === "BountyCreated" ? ethNum(e.args.reward) : 0), color: "var(--s-settle)", foot: "escrowed by buyers since deploy" },
    { k: "Contract events", num: S.events.length, fmt: (v) => fmtInt(Math.round(v)), sub: lastHour ? { cls: "up", txt: `+${lastHour} in the last hour` } : last24 ? { cls: "up", txt: `+${last24} in 24h` } : { cls: "flat", txt: "quiet" }, spark: perBucket(() => 1), color: "var(--s-commit)", scrubFmt: "int", scrubLabel: "events", foot: `${settled} settled · ${term - settled} refunded or cancelled · ${b.length - term} live` },
    { k: "Disputes", num: disputes, fmt: (v) => fmtInt(Math.round(v)), sub: { cls: "flat", txt: rulings.length ? `${rulings.length} ruled` : disputes ? "awaiting ruling" : "none raised" }, spark: cumulative((e) => e.eventName === "Disputed" ? 1 : 0), color: "var(--s-dispute)", scrubFmt: "int", scrubLabel: "disputes", foot: rulings.length ? `rulings: ${rulings.filter((r) => r === 1).length} seller · ${rulings.filter((r) => r === 2).length} buyer · ${rulings.filter((r) => r === 0).length} refused` : "ERC-792 arbitrator rules within the deadline or the reward splits" },
  ];
  const span = sparkSpan();
  $("#stats").innerHTML = tiles.map((t, i) => { const svg = sparkline(t.spark, t.color); const m = sparkline.last; return `<div class="tile ${animate ? "in" : ""}" style="--d:${160 + i * 70}ms"><div class="k">${t.k}</div><div class="v"><span class="num" data-k="${t.k}"></span>${t.unit ? `<small>${t.unit}</small>` : ""}<span class="delta ${t.sub.cls}">${t.sub.txt}</span><span class="hv"></span></div><div class="spark" data-series="${t.spark.map((v) => +v.toFixed(4)).join(",")}" data-xs="${m.xs.join(",")}" data-ys="${m.ys.join(",")}" data-t0="${span.start}" data-step="${span.step}" data-fmt="${t.scrubFmt ?? (t.unit ? "eth" : "int")}" data-label="${t.scrubLabel ?? t.k.toLowerCase()}">${svg}</div><div class="foot">${t.foot}</div></div>`; }).join("");
  for (const t of tiles) { const el = $(`#stats .num[data-k="${t.k}"]`); if (t.num === null) el.textContent = t.fmt(null); else counter(`tile:${t.k}`, el, t.num, t.fmt, { dur: 1100 }); }
}

function renderChart(animate = false) {
  const host = $("#chart");
  if (!S.refreshedAt) { host.innerHTML = `<div class="skel" style="position:absolute;inset:0"></div>`; $("#legend").innerHTML = CATS.map((c) => `<span><i class="c-${c.key}"></i>${c.name}</span>`).join(""); return; }
  const buckets = bucketize(UI.range);
  for (const b of buckets) { for (const k of UI.hiddenCats) b.counts[k] = 0; b.total = Object.values(b.counts).reduce((x, y) => x + y, 0); }
  const W = Math.max(320, host.clientWidth), H = 260, pl = 34, pr = 8, pt = 16, pb = 26;
  const iw = W - pl - pr, ih = H - pt - pb;
  const max = Math.max(1, ...buckets.map((b) => b.total));
  const ticks = niceTicks(max, 4);
  const n = buckets.length, slot = iw / n, bw = Math.max(2, Math.min(28, slot - Math.max(2, slot * 0.35)));
  const y = (v) => pt + ih - (v / ticks[ticks.length - 1]) * ih;
  const stroke = "var(--bg-100)";
  let bars = "";
  buckets.forEach((b, i) => {
    const x = pl + i * slot + (slot - bw) / 2;
    let acc = 0;
    if (b.total) bars += `<g class="stack" data-i="${i}" style="--i:${i}">`;
    for (const c of CATS) {
      const v = b.counts[c.key]; if (!v) continue;
      const y1 = y(acc + v), y0 = y(acc);
      const top = acc + v === b.total;
      bars += top
        ? `<path class="bar" d="${roundTop(x, y1, bw, y0 - y1, Math.min(4, bw / 2))}" fill="${c.color}" stroke="${stroke}" stroke-width="1"/>`
        : `<rect class="bar" x="${x}" y="${y1}" width="${bw}" height="${y0 - y1}" fill="${c.color}" stroke="${stroke}" stroke-width="1"/>`;
      acc += v;
    }
    if (b.total) bars += `</g>`;
  });
  const labelEvery = Math.ceil(n / Math.max(3, Math.floor(iw / 90)));
  const xl = buckets.map((b, i) => (i % labelEvery === 0 ? `<text x="${pl + i * slot + slot / 2}" y="${H - 8}" text-anchor="middle">${esc(bucketLabel(b))}</text>` : "")).join("");
  const gl = ticks.map((t) => `<line x1="${pl}" x2="${W - pr}" y1="${y(t)}" y2="${y(t)}"/><text x="${pl - 8}" y="${y(t) + 4}" text-anchor="end" class="axis">${t}</text>`).join("");
  const stepName = buckets[0].step < 3600 ? `${buckets[0].step / 60} minutes` : buckets[0].step === 3600 ? "hour" : buckets[0].step === 86400 ? "day" : "6 hours";
  host.classList.toggle("animate", animate && !reduceMotion);
  host.innerHTML = `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Contract events per ${stepName}">
    <g class="grid axis">${gl}</g>
    <rect class="band" id="chartBand" x="0" y="${pt}" width="${slot}" height="${ih}" hidden/>
    <line class="base" x1="${pl}" x2="${W - pr}" y1="${pt + ih + .5}" y2="${pt + ih + .5}"/>
    <g>${bars}</g><g class="axis">${xl}</g>
    <line class="cursor" id="chartCursor" x1="0" x2="0" y1="${pt}" y2="${pt + ih}" hidden/>
    <rect class="overlay" x="${pl}" y="${pt}" width="${iw}" height="${ih}" fill="transparent"/>
  </svg><div class="xpill" id="xpill"></div><div class="tooltip" id="tip"></div>`;
  const svgEl = host.querySelector("svg"), tip = $("#tip"), pill = $("#xpill"), band = $("#chartBand"), cur = $("#chartCursor");
  const clear = () => { tip.classList.remove("on"); pill.classList.remove("on"); band.hidden = true; cur.hidden = true; host.removeAttribute("data-active"); host.querySelectorAll(".stack.active").forEach((g) => g.classList.remove("active")); };
  const track = (ev) => {
    const r = host.getBoundingClientRect(); const sx = W / r.width, sy = H / r.height;
    const mx = (ev.clientX - r.left) * sx, my = (ev.clientY - r.top) * sy;
    if (mx < pl || mx > W - pr || my < pt || my > pt + ih) { clear(); return; }
    const i = Math.min(n - 1, Math.max(0, Math.floor((mx - pl) / slot)));
    const b = buckets[i];
    // cursor follows the pointer exactly; the band, focus and popup snap to the bucket under it
    cur.setAttribute("x1", mx); cur.setAttribute("x2", mx); cur.hidden = false;
    band.setAttribute("x", pl + i * slot); band.hidden = false;
    if (host.dataset.active !== String(i)) {
      host.dataset.active = i;
      host.querySelectorAll(".stack.active").forEach((g) => g.classList.remove("active"));
      host.querySelector(`.stack[data-i="${i}"]`)?.classList.add("active");
      const rows = CATS.filter((c) => b.counts[c.key]).map((c) => `<div class="r"><span><i style="background:${c.color}"></i>${c.name}</span><b>${b.counts[c.key]}</b></div>`).join("") || `<div class="r muted"><span>no events in this window</span></div>`;
      tip.innerHTML = `<div class="t">${esc(bucketRange(b))}</div>${rows}${b.total ? `<div class="r total"><span>Total</span><b>${b.total}</b></div>` : ""}`;
    }
    const at = new Date((b.t + ((mx - pl - i * slot) / slot) * b.step) * 1000);
    pill.textContent = at.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" });
    const px = mx / sx, py = my / sy;
    pill.style.setProperty("--x", `${Math.min(r.width - 40, Math.max(40, px))}px`); pill.classList.add("on");
    const flip = px > r.width * 0.62;
    const tx = flip ? px - 16 - tip.offsetWidth : px + 16;
    const ty = Math.min(Math.max(0, py - 28), r.height - tip.offsetHeight - 30);
    tip.style.setProperty("--tx", `${tx}px`); tip.style.setProperty("--ty", `${ty}px`); tip.classList.add("on");
  };
  svgEl.addEventListener("mousemove", track, { passive: true });
  svgEl.addEventListener("mouseleave", clear);
  $("#legend").innerHTML = CATS.map((c) => `<button data-cat="${c.key}" aria-pressed="${!UI.hiddenCats.has(c.key)}" data-tip="Click to ${UI.hiddenCats.has(c.key) ? "show" : "hide"} this stage"><i class="c-${c.key}"></i>${c.name}</button>`).join("");
}
function roundTop(x, y, w, h, r) { r = Math.min(r, h); return `M${x},${y + h}V${y + r}a${r},${r} 0 0 1 ${r},-${r}h${w - 2 * r}a${r},${r} 0 0 1 ${r},${r}V${y + h}Z`; }
function niceTicks(max, count) { const raw = max / count; const p = 10 ** Math.floor(Math.log10(raw)); const step = [1, 2, 5, 10].map((m) => m * p).find((s) => s >= raw); const top = Math.ceil(max / step) * step; const out = []; for (let v = 0; v <= top + 1e-9; v += step) out.push(v); return out; }
function bucketLabel(b) { const d = new Date(b.t * 1000); return b.step >= 86400 ? d.toLocaleDateString([], { month: "short", day: "numeric" }) : b.step < 3600 ? d.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }) : d.toLocaleTimeString([], { hour: "numeric" }) + (b.step === 3600 ? "" : ` ${d.toLocaleDateString([], { month: "short", day: "numeric" })}`); }
function bucketRange(b) { const a = new Date(b.t * 1000), z = new Date((b.t + b.step) * 1000); return b.step >= 86400 ? a.toLocaleDateString([], { weekday: "short", month: "short", day: "numeric" }) : `${a.toLocaleDateString([], { month: "short", day: "numeric" })} ${a.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })} – ${z.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}`; }

function renderFunnel(animate = false) {
  if (!S.refreshedAt) { $("#funnel").innerHTML = Array.from({ length: 6 }, (_, i) => `<div class="step"><span class="n">${i + 1}</span><div><div class="name skel">loading stage</div><div class="bar"></div></div><span class="cnt skel">0</span></div>`).join(""); return; }
  const c = stageCounts(), max = Math.max(1, c.created);
  const steps = [
    ["Created", "buyer escrowed a reward", c.created, "created"],
    ["Committed", "seller bonded a hidden bundle", c.committed, "committed"],
    ["Sampled", "blockhash-picked tasks revealed with proofs", c.sampled, "sampled"],
    ["Approved", "buyer judged the sample sound", c.approved, "approved"],
    ["Delivered", "ciphertext posted to the buyer's key", c.delivered, "delivered"],
    ["Accepted", "buyer reran the claims and paid", c.accepted, "accepted"],
  ];
  const go = animate && !reduceMotion;
  const tipFor = (k) => c.ids[k].length ? `${c.ids[k].length} bount${c.ids[k].length === 1 ? "y" : "ies"} reached this step: ${c.ids[k].join(" ")}` : "No bounty has reached this step yet";
  for (const [k, n] of Object.entries(c.ids)) { const li = $(`#flow [data-stage="${k}"]`); if (!li) continue; li.classList.toggle("on", n.length > 0); li.setAttribute("data-tip", tipFor(k)); counter(`flow:${k}`, li.querySelector(".cnt"), n.length, (x) => String(Math.round(x)), { dur: 900 }); }
  $("#funnel").innerHTML = steps.map(([n, d, v, k], i) => `<div class="step" data-tip="${tipFor(k)}"><span class="n ${v && !go ? "on" : ""}">${i + 1}</span><div><div class="name">${n} <span class="desc">· ${d}</span></div><div class="bar"><i data-w="${(v / max) * 100}" style="width:${go ? 0 : (v / max) * 100}%"></i></div></div><span class="cnt" data-k="${n}"></span></div>`).join("")
    + `<div class="term"><span class="badge red" data-tip="${tipFor("disputed")}">${c.disputed} disputed</span><span class="badge green" data-tip="${tipFor("settled")}">${c.settled} settled</span><span class="badge purple" data-tip="${tipFor("refunded")}">${c.refunded} refunded</span><span class="badge gray" data-tip="${tipFor("split")}">${c.split} split</span></div>`;
  steps.forEach(([n, , v]) => counter(`funnel:${n}`, $(`#funnel .cnt[data-k="${n}"]`), v, (x) => String(Math.round(x)), { dur: 900 }));
  if (go) requestAnimationFrame(() => requestAnimationFrame(() => {
    $$("#funnel .bar i").forEach((el, i) => { el.style.transitionDelay = `${i * 60}ms`; el.style.width = `${el.dataset.w}%`; });
    $$("#funnel .step").forEach((st, i) => { const v = steps[i][2]; if (v) setTimeout(() => st.querySelector(".n").classList.add("on"), 150 + i * 60); });
  }));
}

function bandHTML(s) {
  const w = Number(s.weakMaxBps) / 100, st = Number(s.strongMinBps) / 100;
  return `<div class="band" data-tip="Difficulty band on pinned models: ${esc(s.weakModel)} must score ≤ ${w}%, ${esc(s.strongModel)} ≥ ${st}%, an empty-answer policy ≤ ${pct(s.nullMaxBps)}. Claims are checked to ±${pct(s.toleranceBps)}."><div class="lbl"><span>${esc(s.weakModel)} ≤ ${w}%</span></div><div class="track"><span class="weak" style="width:${w}%"></span><span class="strong" style="width:${100 - st}%"></span></div><div class="lbl"><span>${esc(s.strongModel)} ≥ ${st}%</span><span>±${pct(s.toleranceBps)}</span></div></div>`;
}
function matches(i, b) {
  const st = STATUS[b.status];
  if (UI.status === "live" ? !LIVE.has(st) : UI.status !== "all" && st !== UI.status) return false;
  if (!UI.q) return true;
  const hay = `#${i} ${b.spec.domainTag} ${b.spec.weakModel} ${b.spec.strongModel} ${b.buyer} ${b.seller} ${st} ${who(b.buyer)} ${who(b.seller)}`.toLowerCase();
  return UI.q.split(/\s+/).every((w) => hay.includes(w));
}
function renderBounties() {
  const tbody = $("#bounties tbody"); const rows = [];
  const total = S.bounties.length; let shown = 0;
  for (let i = total - 1; i >= 0; i--) {
    const b = S.bounties[i]; if (!b || !matches(i, b)) continue; shown++;
    const s = b.spec, st = STATUS[b.status];
    const evs = S.byId[String(i)] ?? []; const last = evs[evs.length - 1];
    const open = UI.expanded.has(i);
    rows.push(`<tr class="row" data-i="${i}" aria-expanded="${open}">
      <td><svg class="chev" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.6"><path d="m6 3 5 5-5 5"/></svg></td>
      <td class="num">#${i}</td>
      <td><span class="pill s-${st}">${st}</span></td>
      <td><div class="nowrap">${esc(s.domainTag)}</div><div class="faint label-12 nowrap">${s.taskCount} tasks · reveal ${s.sampleSize} · ${s.runs} run${s.runs === 1 ? "" : "s"}</div></td>
      <td>${bandHTML(s)}</td>
      <td class="r num">${eth(b.reward)}${b.sellerBond > 0n ? `<div class="faint">bond ${eth(b.sellerBond)}</div>` : ""}</td>
      <td>${addr(b.buyer)}</td><td>${addr(b.seller)}</td>
      <td class="nowrap">${last ? `<div>${last.eventName}</div><div class="faint label-12" data-tip="${tsOf(last) ? fmtDateTime(tsOf(last)) : ""}">${tsOf(last) ? rel(tsOf(last)) : ""} ${tx(last.transactionHash, "")}</div>` : `<span class="faint">—</span>`}</td></tr>`);
    if (open) rows.push(`<tr class="detail"><td colspan="9">${detailHTML(i, b, evs)}</td></tr>`);
  }
  tbody.innerHTML = rows.join("") || `<tr><td colspan="9" class="empty">${total ? "No bounties match this filter." : "No bounties yet. Run the buyer agent to post one."}</td></tr>`;
  $("#cntBounties").textContent = total;
  $("#bountySub").textContent = total ? `${shown} of ${total}` : "";
}
function detailHTML(i, b, evs) {
  const lastCommit = evs.map((e) => e.eventName).lastIndexOf("Committed");
  const revealed = evs.filter((e, k) => e.eventName === "SampleRevealed" && k > lastCommit);
  const terminal = ["Settled", "Refunded", "Cancelled"].includes(STATUS[b.status]);
  const dl = terminal ? [] : [["approve by", b.approveBy], ["deliver by", b.deliverBy], ["verify by", b.verifyBy], ["rule by", b.ruleBy]].filter(([, t]) => Number(t) > 0);
  const now = Date.now() / 1000;
  return `<div class="detail-grid detail">
    <div><h4>Timeline</h4><ul class="timeline">${evs.map((e) => `<li class="${catOf(e.eventName)}"><span class="t">${tsOf(e) ? fmtTime(tsOf(e)) : `#${e.blockNumber}`}</span><span class="e">${e.eventName}</span>${narrate(e)} ${tx(e.transactionHash, "")}</li>`).join("")}</ul></div>
    <div>
      ${dl.length ? `<h4>Deadlines</h4><div class="deadlines">${dl.map(([k, t]) => `<span class="badge ${Number(t) < now ? "gray" : "amber"}">${k} ${fmtDateTime(t)} · ${rel(t)}</span>`).join("")}</div>` : ""}
      <h4>Revealed sample · current commit</h4>
      ${revealed.length ? revealed.map((e) => { const t = parseTask(e.args.task); if (!t) return ""; return `<div class="task"><div class="hd"><b>task ${e.args.index}</b><span>${esc(t.family)} · d${t.difficulty}</span><span>${esc(t.grader?.type ?? "")}</span></div><div class="p">${esc(t.prompt)}</div><div class="ref">reference <b>${esc(t.reference)}</b></div></div>`; }).join("") : `<div class="faint copy-13">Nothing revealed yet. The seller reveals only the indices that blockhash(sampleBlock) selects.</div>`}
      <div class="kv"><b>task root</b><span>${b.taskRoot}</span><b>bundle hash</b><span>${b.bundleCommitment}</span><b>sample block</b><span>${b.sampleBlock}</span><b>buyer X25519</b><span>${b.buyerPubKey}</span>${b.ciphertextHash && !/^0x0+$/.test(b.ciphertextHash) ? `<b>ciphertext hash</b><span>${b.ciphertextHash}</span>` : ""}<b>run params</b><span>${b.spec.runParamsHash}</span></div>
    </div></div>`;
}

function record(r) {
  const { good, bad } = r;
  if (!good && !bad) return `<span class="faint">no record yet</span>`;
  return `<span class="badge ${bad ? (good ? "amber" : "red") : "green"}">${good} clean · ${bad} mark${bad === 1 ? "" : "s"}</span>`;
}
function renderReputation() {
  const n = (v) => `<td class="r num">${v ?? 0}</td>`;
  $("#sellers tbody").innerHTML = S.sellers.map((a, i) => { const r = S.srep[i]; const good = Number(r[5] ?? 0) + Number(r[6] ?? 0), bad = Number(r[1] ?? 0) + Number(r[2] ?? 0) + Number(r[4] ?? 0) + Number(r[7] ?? 0); return `<tr><td>${addr(a)}</td>${r.slice(0, 8).map(n).join("")}<td class="r num">${eth(r[8] ?? 0n)}</td><td>${record({ good, bad })}</td></tr>`; }).join("") || `<tr><td colspan="11" class="empty">No sellers have committed yet.</td></tr>`;
  $("#buyers tbody").innerHTML = S.buyers.map((a, i) => { const r = S.brep[i]; const good = Number(r[1] ?? 0), bad = Number(r[3] ?? 0); return `<tr><td>${addr(a)}</td>${r.map(n).join("")}<td>${record({ good, bad })}</td></tr>`; }).join("") || `<tr><td colspan="6" class="empty">No buyers yet.</td></tr>`;
}

function renderLog() {
  const log = $("#log"); const atBottom = log.scrollHeight - log.scrollTop - log.clientHeight < 40 || !log.innerHTML;
  const evs = S.events.filter((e) => UI.logCats.has(catOf(e.eventName)));
  log.innerHTML = evs.map((e) => { const c = CATS.find((x) => x.key === catOf(e.eventName)); const isNew = S.events.indexOf(e) >= newFrom; return `<div class="ln${isNew ? " new" : ""}"><span class="t">${tsOf(e) ? fmtTime(tsOf(e)) : `#${e.blockNumber}`}</span><span class="ev"><i style="background:${c.color}"></i>${e.eventName}</span><span class="m">${narrate(e)}</span>${tx(e.transactionHash, "")}</div>`; }).join("") || `<div class="empty" style="padding:28px;text-align:center" class="faint">No events yet.</div>`;
  if (atBottom) log.scrollTop = log.scrollHeight;
  $("#cntLog").textContent = S.events.length;
  $("#logChips").innerHTML = CATS.map((c) => `<button class="chip" data-cat="${c.key}" aria-pressed="${UI.logCats.has(c.key)}"><i class="c-${c.key}"></i>${c.name}</button>`).join("");
}

// ---------- interaction ----------
function setTab(t) {
  UI.tab = t;
  $$("#tabs [role=tab]").forEach((b) => b.setAttribute("aria-selected", b.dataset.tab === t));
  $$("[data-panel]").forEach((p) => { p.hidden = p.dataset.panel !== t; });
  history.replaceState(null, "", `#${t}`);
}
document.addEventListener("click", (ev) => {
  const tab = ev.target.closest("[data-tab]"); if (tab) { setTab(tab.dataset.tab); if (!tab.closest("#tabs")) $("#tabs").scrollIntoView({ behavior: "smooth", block: "start" }); return; }
  const range = ev.target.closest("#rangeSeg button"); if (range) { setRange(range.dataset.range, true); renderChart(true); return; }
  const leg = ev.target.closest("#legend button"); if (leg) { const k = leg.dataset.cat; UI.hiddenCats.has(k) ? UI.hiddenCats.delete(k) : UI.hiddenCats.add(k); renderChart(true); return; }
  const status = ev.target.closest("#statusSeg button"); if (status) { UI.status = status.dataset.status; $$("#statusSeg button").forEach((b) => b.setAttribute("aria-pressed", b === status)); renderBounties(); return; }
  const chip = ev.target.closest("#logChips .chip"); if (chip) { const k = chip.dataset.cat; UI.logCats.has(k) ? UI.logCats.delete(k) : UI.logCats.add(k); renderLog(); return; }
  const row = ev.target.closest("tr.row"); if (row && !ev.target.closest("a")) { const i = +row.dataset.i; UI.expanded.has(i) ? UI.expanded.delete(i) : UI.expanded.add(i); renderBounties(); return; }
});
$("#search").addEventListener("input", (ev) => { UI.q = ev.target.value.trim().toLowerCase(); renderBounties(); });
$("#themeBtn").addEventListener("click", () => {
  const cur = document.documentElement.dataset.theme || (matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
  const next = cur === "dark" ? "light" : "dark";
  document.documentElement.dataset.theme = next;
  try { localStorage.setItem("eb-theme", next); } catch {}
});
let rt; addEventListener("resize", () => { clearTimeout(rt); rt = setTimeout(() => renderChart(false), 120); });

// ---------- mouse layer ----------
const gtip = $("#gtip");
let tipEl = null;
function showTip(el) {
  tipEl = el;
  gtip.textContent = el.dataset.tip; gtip.classList.toggle("mono", el.hasAttribute("data-tip-mono"));
  const r = el.getBoundingClientRect(); const below = r.top < 90;
  gtip.classList.toggle("below", below);
  gtip.style.left = `${Math.min(innerWidth - 24, Math.max(24, r.left + r.width / 2))}px`;
  gtip.style.top = `${below ? r.bottom : r.top}px`;
  gtip.classList.add("on");
}
document.addEventListener("mouseover", (ev) => { const el = ev.target.closest("[data-tip]"); if (el && el !== tipEl) showTip(el); else if (!el && tipEl) { tipEl = null; gtip.classList.remove("on"); } });
document.addEventListener("mouseout", (ev) => { if (tipEl && !tipEl.contains(ev.relatedTarget)) { tipEl = null; gtip.classList.remove("on"); } });
document.addEventListener("scroll", () => { if (tipEl) showTip(tipEl); }, { passive: true });
document.addEventListener("mousemove", (ev) => {
  const el = ev.target.closest(".card, .tile, .status-card, .flow li");
  if (el) { const r = el.getBoundingClientRect(); el.style.setProperty("--mx", `${ev.clientX - r.left}px`); el.style.setProperty("--my", `${ev.clientY - r.top}px`); }
  const sp = ev.target.closest(".spark");
  if (sp) scrub(sp, ev);
}, { passive: true });
$("#hero").addEventListener("mousemove", (ev) => { const r = $("#hero").getBoundingClientRect(); $("#hero").style.setProperty("--hx", `${ev.clientX - r.left}px`); $("#hero").style.setProperty("--hy", `${ev.clientY - r.top}px`); }, { passive: true });
document.addEventListener("mouseout", (ev) => { const sp = ev.target.closest?.(".spark"); if (sp && !sp.contains(ev.relatedTarget)) sp.closest(".tile").classList.remove("scrub"); });
function scrub(sp, ev) {
  const xs = sp.dataset.xs.split(",").map(Number), ys = sp.dataset.ys.split(",").map(Number), series = sp.dataset.series.split(",").map(Number);
  const r = sp.getBoundingClientRect(); const px = ((ev.clientX - r.left) / r.width) * 100;
  let i = 0; for (let k = 1; k < xs.length; k++) if (Math.abs(xs[k] - px) < Math.abs(xs[i] - px)) i = k;
  sp.querySelector(".guide").style.left = `${xs[i]}%`;
  const pt = sp.querySelector(".pt"); pt.style.left = `${xs[i]}%`; pt.style.top = `${ys[i]}%`;
  const t = new Date((Number(sp.dataset.t0) + i * Number(sp.dataset.step)) * 1000);
  const v = sp.dataset.fmt === "eth" ? `${series[i].toFixed(3)} ETH` : fmtInt(series[i]);
  const tip = sp.querySelector(".stip");
  tip.innerHTML = `<b>${v}</b> ${esc(sp.dataset.label)}<span class="when">${t.toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</span>`;
  tip.style.left = `${xs[i]}%`; tip.style.top = `${ys[i]}%`;
  tip.classList.toggle("edge-l", xs[i] < 22); tip.classList.toggle("edge-r", xs[i] > 78); tip.classList.toggle("below", ys[i] < 45);
  sp.closest(".tile").classList.add("scrub");
}
if (["bounties", "reputation", "log"].includes(location.hash.slice(1))) setTab(location.hash.slice(1));

renderAll();
refresh();
setInterval(refresh, 10_000);
