// Generated by agents/src/deploy.ts on 2026-09-11T03:28:39.324Z
window.EVALBOUNTY_CONFIG = {
  chainId: 11155111,
  contractAddress: "0x6b7f34fa4229aa9545b08c47d187415505c0e7a8",
  arbitratorAddress: "0x5d16caa1e9789a996839aa44a4167b574b887653",
  deployBlock: 11679290,
  rpcUrl: "https://ethereum-sepolia-rpc.publicnode.com",
  explorerBase: "https://sepolia.etherscan.io",
  arbiterPubKey: "0x7f0052ad83f08d3a73f490cf9f42858bf93384a10a6a4c0c10c1e34d493d8435",
  agents: {
    buyer: "0x017082D0C34ca98ff11F6D779a15363f8592aa4B",
    seller: "0xF9f078100D16d052F658e21eBF417C3C095A66de",
    arbiter: "0x4D9128F607Afe88660873dc0EDE85F507f3f98a0",
    junkSeller: "0xC8D64B575800cC434D97D3887034fEb8b24C7952"
  }
};
